services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:Z  # Lo :Z serve per i permessi su Fedora/SELinux
    depends_on:
      - db

  db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=clinica_veterinaria
      - MYSQL_USER=user_clinica
      - MYSQL_PASSWORD=password_segreta
    ports:
      - "3306:3306"
    volumes:
      # Se hai un file .sql nella cartella /SQL, questo lo esegue all'avvio!
      - ./SQL:/docker-entrypoint-initdb.d:Z